services:
  postgres:
    image: postgres:16
    container_name: favly_postgres
    environment:
      - POSTGRES_USER=FlDay
      - POSTGRES_PASSWORD=S3flat123
      - POSTGRES_DB=Flavly_db
    ports:
      - "5433:5433"
    volumes:
    - pgdata:/var/lib/postgresql
    
  favly.api:
    image: ${DOCKER_REGISTRY-}favlyapi
    build:
      context: Favly.api
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5433;Database=Flavly_db;Username=FlDay;Password=S3flat123
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

volumes:
  pgdata:
  

      